development:
  adapter: postgresql
  encoding: unicode
  database: travel_planner_development
  pool: 5
  username: igendou
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: travel_planner_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: travel_planner_production
  pool: 5
  username: igendou
  password:
  host: 127.0.0.1
  port: 5432

