development:
  sessions:
    default:
      database: travel_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: travel_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: travel_production
      hosts:
        - localhost:27017
